# Generated by Django 5.0 on 2024-01-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Dob', models.CharField(default='', max_length=20)),
                ('Phno', models.IntegerField(default=0)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('Conpass', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
